### ISSUE TITLE
Legend Position on function()

### ISSUE THREAD

**Issue by thiagoshima** [rsheldiii/KeyV2#10]
**What version of OpenSCAD are you on?**
2019.08.04.ci3200 (git 4952cb9a)

**Describe the bug**
nothing happens when the position is changed in the legend function

**To Reproduce**
1. Go to 'keys.scad'
2. paste following code `legend("F7",[-1,0],3) cherry() oem_row(n=1) key(); `
4. the key legend don't get moved

**Comment by rsheldiii** [comment]
good catch. should be all set, pull and try again?

**Comment by danielo515** [comment]
Oh, this bug is affecting me too

**Comment by danielo515** [comment]
> @danielo515 is this affecting you even after you pull the most recent code? It should have been fixed with [these changes](https://github.com/rsheldiii/KeyV2/pull/11/files)

Yeah, it is working. The problem is that I was providing a locale property that was an object instead of a string. It is weird that it triggers the same error as when you register a locale. My bad this time

**Comment by danielo515** [comment]
@rsheldiii nope. As I mentioned on #56 the problem is cloning your main repo as instructed on the readme instead of clonning this repository.
It is working without problems by now
