### ISSUE TITLE
New to openscad and I don't know how to use the command to add stl models

### ISSUE THREAD

**Issue by PressXFor** [rsheldiii/KeyV2#107]
`cherry() key() {
  translate([-6.25,2.3,-0]) scale(0.074) import("Assieme1.stl");
};`

I copy pasted that code and changed the name to whatever stl I'm using, and I can't get it to show up. I tried puting it in the same folder as OpenScad and the same folder as the customizer.scad.

**Comment by mrebersv** [comment]
This is not an issue with the repo.  Your STL file should either be in the same folder as whatever .scad file you're using to render (key.scad, for instance), OR it will need a path added to the file.  

You should close this ticket and use an appropriate forum for OpenSCAD help in the future.

**Comment by rsheldiii** [comment]
@mrebersv is right, [`import`](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/STL_Import_and_Export) is an openSCAD  directive, it should work just fine if the stl is in the same folder as the script. Let's close this, feel free to shoot me an email if you need more help
