### ISSUE TITLE
g20_row() spacebar() key(); produces closed-bottom key

### ISSUE THREAD

**Issue by ironiridis** [rsheldiii/KeyV2#110]
**What version of OpenSCAD are you on?**
2021.01

**Describe the bug**
```
g20_row() spacebar() key();
```

Render and preview have closed bottom with no stems:
![image](https://user-images.githubusercontent.com/308159/128442563-31dfa4b0-690b-4379-b6c8-f6a3622727ab.png)

**Comment by rsheldiii** [comment]
Looks like assuming all spacebars have a sideways cylindrical dish was the culprit. Thanks for reporting this!
