### ISSUE TITLE
How do I choose cherry profile in OpenSCad customizer?

### ISSUE THREAD

**Issue by NovaViper** [rsheldiii/KeyV2#112]
Hey, im trying to generate some cherry profile keycaps but im not sure what parameter to use, as it doesn't list cherry as an option at all. Is it possible to make cherry profile caps in the program at this time?

**Comment by rsheldiii** [comment]
After the v2.0.0 merge, `cherry` is now a profile selection as in `preonic_default("cherry")` or `cherry_row(5)`. OEM was close before, but not quite the same.
