### ISSUE TITLE
An option to print the legend on the side? 

### ISSUE THREAD

**Issue by TheDorje** [rsheldiii/KeyV2#12]
I was looking for a way to print the legend on the side of the keycap instead of on the top. 
I couldn't find a way to do it. Is it coded in? If not, would it be difficult to add it? :)

**Comment by rsheldiii** [comment]
Unlike the top of the keycap there's no static definition of the side of a keycap, especially now that there are three different ways to generate it. Though, I suppose there is a 'normal' side, in that a regular keycap with no side sculpting has a straight front. you'd have to do some trigonometry to get it though; you'd have to find the leading edge of the top of the keycap, which is affected by skew and tilt, and then you can say the line between the bottom edge of the keycap and that top edge is the front.

I might take a look into this, I originally thought it wasn't easily generalizable but maybe you could pull it off.

**Comment by rsheldiii** [comment]
fixed! use `$front_print_legends = true` to turn this on.
