### ISSUE TITLE
Is it possible to change the font of the legends?

### ISSUE THREAD

**Issue by JoakoV3** [rsheldiii/KeyV2#122]
I want to put icons on the legends like arrows but is not supported natively. Is there a way to change the font or to add icons without uploading an stl?

**Comment by czyz** [comment]
It is possible to change the font. I did it like so:

`use </Users/myusername/Library/Fonts/BRAILLE1.ttf>
$font="Braille Normal:style=Regular";`

I also added "$outset_legends = true;" as I'm hoping to get familiar with braille while learning a new layout.

**Comment by rsheldiii** [comment]
@czyz's got it!
