### ISSUE TITLE
Row sequence？

### ISSUE THREAD

**Issue by kahoch** [rsheldiii/KeyV2#14]
I'm confused by the row order. Which one is correct?

5 -> F keys
1 -> Number row
2 -> Tab row
3 -> Caps row
4 -> Shift & Ctrl row

Or 

5 -> F keys
4 -> Number row
3 -> Tab row
2 -> Caps row
1 -> Shift & Ctrl row

**Comment by rsheldiii** [comment]
Hi! I modified this recently. The gist of it is I was dutifully going by Signature Plastic's official row listings when I had them: [SA family](https://pimpmykeyboard.com/template/images/SAFamily.pdf) [DCS family](https://pimpmykeyboard.com/template/images/DCSFamily.pdf) but I'm switching to a new system. 

Before you'd have to follow the row recommendations for each profile. In the new world, anything outside of [1,2,3,4] is assumed to be row 5, and row 5 is function row, so now you can even do stuff like this:

```
for (x = [0:1:4]) {
  translate_u(0,-x) legend(legends[x]) dcs_row(x, 0) {
    key();
  }
}
```

and that will generate a full row of keycaps in their correct orientation, save for the spacebar row, which is still profile-specific.
