### ISSUE TITLE
Syntax Error in settings.scad

### ISSUE THREAD

**Issue by wcunning** [rsheldiii/KeyV2#154]
**What version of OpenSCAD are you on?**
OpenSCAD version 2019.05

**Description**
Fresh clone, with the above OpenSCAD version from a very recently set up Ubuntu 20.04 LTS gives the following error:

Loaded design '/home/wcunning/projects/dactyl-manuform/KeyV2/keys.scad'.
ERROR: Parser error in file "/home/wcunning/projects/dactyl-manuform/KeyV2/src/settings.scad", line 217: syntax error 
Execution aborted

Same thing with other examples from the examples folder.

**Comment by wcunning** [comment]
Syntax error complaint disappears when I revert to the 2.0.0 Merge commit on the settings.scad file alone. I'm not very good with scad, so I'm not sure what the syntax issue actually is, but that should help narrow it down.

**Comment by wcunning** [comment]
On top of that, I can't seem to get any profile but DCS to generate -- the sa_ergo.scad example doesn't work, nor does setting the keys.scad file to other profiles seem to work. I just get a stem, no cap.

**Comment by pietchaki** [comment]
Try updating your OpenScad Software. I had this issue and was running an older version, updated to the 2021.01 and fixed.

**Comment by stonepreston** [comment]
I faced the same problem. I was indeed able to fix it by installing a newer version of openscad. I was on ubuntu and I guess the 20.04 repos are not very up to date. I installed via the openscad snap and got a fresh version and was able to do things just fine after that.

**Comment by rsheldiii** [comment]
sounds like this is resolved, thanks for chiming in everyone. I could probably throw a disclaimer about old versions in the readme somewhere
