### ISSUE TITLE
Protuding key legend instead of recessed

### ISSUE THREAD

**Issue by edasque** [rsheldiii/KeyV2#158]
Hi,

I was able to do it in V1 (though I can't remember how) but I can't figure it out in V2 how to make it protrude instead of being recessed. Negative values of ```inset_legend_depth``` do not work.

Is it possible in some way, @rsheldiii ?

Thank you in advance.

**Comment by tsjost** [comment]
You can make the legend protrude by setting `$outset_legends = true;`

To change how much it protrudes, it might work to go into `src/key.scad` and inside `module additive_features` change the `0` in `if($outset_legends) legends(0);` to whichever value you want, and then in `src/features/legends.scad` change `translate([woffset, hoffset, -depth]){` into `translate([woffset, hoffset, 0]){` :smile:

**Comment by edasque** [comment]
@tsjost that worked, thank you. I wonder if it can be incorporated as options easily.
