### ISSUE TITLE
DSA option gives incorrect results

### ISSUE THREAD

**Issue by 666dsa666** [rsheldiii/KeyV2#162]
**What version of OpenSCAD are you on?**
2022.05.15.ci11888 (git 6aae79634)

**Describe the bug**
DSA key profile option don't generate DSA profiled key

**To Reproduce**
Choose DSA option
Generate key

![image](https://user-images.githubusercontent.com/11072018/169382319-fdd2fee6-067c-488b-9d33-000c2fb07805.png)
![image](https://user-images.githubusercontent.com/11072018/169382341-ae01d31c-0fad-4ae4-a7bd-0d1ee1d84d6a.png)
![image](https://user-images.githubusercontent.com/11072018/169382381-36050761-d8e0-47c6-8d04-6a19d92434f0.png)

**Comment by Tentoe** [comment]
Referenced from [here](https://github.com/rsheldiii/KeyV2/blob/ec44ef76dee1e271a059fb7696a5c7675bd671ce/src/layouts/60_percent/default.scad#L19) and [here](https://github.com/rsheldiii/KeyV2/blob/ec44ef76dee1e271a059fb7696a5c7675bd671ce/src/layouts/layout.scad#L23). 

`layout(60_percent_default_layout, "dsa", 60_percent_legends, row_override=3);` seems to work. Just find your layout in the layouts folder.

**Comment by mr-september** [comment]
Thank you! Works great :)

**Comment by rsheldiii** [comment]
with the full switchover to `simple_layout` (which hasn't happened yet) it's easier to control this:

```
simple_layout(preonic_default_layout) {
  dsa_row(3, $column){
    key();
  }
}
```

![image](https://user-images.githubusercontent.com/510867/195957326-9f1c14b8-60bf-4e86-bd2a-2b0855ea1e57.png)

sounds like this is resolved, closing. Thanks Tentoe for chiming in!
