### ISSUE TITLE
Keys have v-shaped cutouts in all files

### ISSUE THREAD

**Issue by coxfuture** [rsheldiii/KeyV2#176]
**What version of OpenSCAD are you on?**
Let me know what version of OpenSCAD you have to better diagnose the issue
2021.01

**Describe the bug**
![image](https://user-images.githubusercontent.com/42841489/204432293-0b7dea73-b385-4db1-9642-da5cbb391c61.png)
![image](https://user-images.githubusercontent.com/42841489/204433205-208c5e16-0d04-4adc-906f-acf064a5e155.png)

see image. any key I try to make is this shape, nothing I change does anything at all. 60_percent_default makes a bunch of keys, but all are the same shape.
customizer.scad and keys.scad both produce same behavior

**Additional context**
This is the first time I've used openscad. I may just be missing an important step.

Thingiverse version (the .scad included in the download) worked fine except for dish types, but I was unable to get this repo working at all

**Comment by coxfuture** [comment]
Fixed by updating openscad to development snapshot

**Comment by Tanky08** [comment]
> Fixed by updating openscad to development snapshot

can you change the instructions to says you have yo have the developer version
