### ISSUE TITLE
Key sculpting appears to have broken recently

### ISSUE THREAD

**Issue by RyuKojiro** [rsheldiii/KeyV2#182]
**What version of OpenSCAD are you on?**
2021.01

**Describe the bug**
`src/key.scad` Before:
<img width="402" alt="Screenshot 2023-01-05 at 9 38 22 PM" src="https://user-images.githubusercontent.com/3972033/210782162-5dec7764-519f-4b29-810e-7c800fa89108.png">

`src/key.scad` After:
<img width="387" alt="Screenshot 2023-01-05 at 9 38 30 PM" src="https://user-images.githubusercontent.com/3972033/210782313-1132c77f-2a92-431f-9d75-eee7f717ee95.png">

I did a bisect, which indicated e88a398f7a892996269f48c89ae541ece3bb556c is the first bad commit.

When working with different source that doesn't include the same things as `key.scad`, I've seen stuff where only a cylinder cut out of the middle of the key is left behind. e.g. before:
<img width="377" alt="Screenshot 2023-01-05 at 9 44 58 PM" src="https://user-images.githubusercontent.com/3972033/210784340-395a95d1-9fdc-48f2-bbf4-f38f1d3f3636.png">

After:
<img width="380" alt="Screenshot 2023-01-05 at 9 51 40 PM" src="https://user-images.githubusercontent.com/3972033/210784499-fb98039a-7097-4811-87d9-2c04fbab516c.png">

**To Reproduce**
Open `src/key.scad`

**Comment by Llamalland** [comment]
I'm having the same problem. Legends also seem to be broken for me, but that might be a separate issue

**Comment by MacD5** [comment]
I'm having this issue as well. Has there been a solution for it yet?

**Comment by artursvanags** [comment]
This could be due to OpenSCAD version, I remember the author of this GitHub said to use the latest development builds e.g. 2023.01.18 as they contain libraries that the program uses. Report back if this solves the problem.

**Comment by MacD5** [comment]
I totally forgot about that. Thanks, that was it.

**Comment by Llamalland** [comment]
Works for me too, thanks @showtek320

**Comment by RyuKojiro** [comment]
> This could be due to OpenSCAD version, I remember the author of this GitHub said to use the latest development builds e.g. 2023.01.18 as they contain libraries that the program uses. Report back if this solves the problem.

Yep, it works with the latest development build. Thanks!
