### ISSUE TITLE
Is it be possible to create multiple lines of text?

### ISSUE THREAD

**Issue by danielo515** [rsheldiii/KeyV2#56]
Hello,
Thanks for sharing this amazing work with the world.

I was guessing if it will be possible to create two lines of text on the same keycap. Something like the may and secondary function of the key. Or maybe being able to position a different text on each corner, or something like that.

Thanks!

**Comment by danielo515** [comment]
Hello again. I just saw the docs for legend and shaw the issue #21 , however I don't get any success in moving the legends around, they appear all on top of each other. This is the code I'm using:

```
use <src/key.scad>

include <src/settings.scad>
include <src/key_sizes.scad>
include <src/key_profiles.scad>
include <src/key_types.scad>
include <src/key_transformations.scad>


//$has_brim=true;
$font_size = 3;
$inverted_dish = true;
$key_length = 1;
$outset_legends = true;

 dcs_row(1) {
     $dish_type =  "sideways cylindrical";
     legend("P",[0,-1],5)
     legend("E",[0,1],8)

     key();
 }

```

**Comment by danielo515** [comment]
Ok, found the bug, it is on the readme 🤣
this line: 
```
git clone https://github.com/rsheldiii/openSCAD-projects.git
```
Clones your personal project, at first I was confused about it, but I took the docs as correct. I just tried to clone *this* repository and things now work as they should. I recommend to update the readme.

Regards

**Comment by rsheldiii** [comment]
ach, I'm sorry about that. this project used to be inside that project, it looks like I moved it without updating the links :/ I merged the PR that fixes this in the docs so I'm gonna close this issue, thank you both for being so helpful with this! crazy to think I've been telling people to download the wrong code for _years_ now

**Comment by danielo515** [comment]
NP! The proyect itself is awsome
