### ISSUE TITLE
How do i indent the legends 

### ISSUE THREAD

**Issue by maxgafner** [rsheldiii/KeyV2#6]
Hello I am new to coding and I wanted to ask how do I indent text on a keycap that i am making. I dont know if this is the right place to ask or not. Thank you ahead of time for the assistance

**Comment by wiiliam** [comment]
Not sure if this is what you mean, but go into customizer.scad and look for "inset" and set it to true. It should be line 2055

Screenshot: https://i.imgur.com/uhFF3Pl.png

**Comment by rsheldiii** [comment]
sorry for the late response, notifications haven't been going to the right email for this repo. `inset` is definitely what you should be looking for
