### ISSUE TITLE
How can i create the 60% Layout in OpenSCAD? (How can i import the 60_percent_default("dcs") key(); into OpenSCAD?)

### ISSUE THREAD

**Issue by maxwefter** [rsheldiii/KeyV2#62]
Sorry i am a complete noob in coding but i want to learn. I really love this easy to use code you have created but i have this question: to generate single keycaps is quite simple but on this github page there is a topic called layout. I was just wondering where i have to insert this: 60_percent_default("dcs") key(); in the code to create multiple keys at once?
Sorry if im just too blind to see the obvious answer! Thank you for this and i would really appreciate help!
Thanks again and kind regards
maxwefter

**Comment by maxwefter** [comment]
Alright, i found the files in the Keyv2 master folder. So now its jsut a question of implementation

**Comment by AaronVerDow** [comment]
You can call 60_percent_default from KeyV2/keys.scad

This file by default includes includes.scad which in turn includes everything you'll need from src/

I always open KeyV2/keys.scad in OpenSCAD to see what I'm doing and then just use a text editor to mess with the files in src without previewing them directly.

**Comment by maxwefter** [comment]
Thank you so much!
-------- Ursprüngliche Nachricht --------Von: AaronVerDow ***@***.***> Datum: 22.03.21  04:52  (GMT+01:00) An: rsheldiii/KeyV2 ***@***.***> Cc: maxwefter ***@***.***>, Author ***@***.***> Betreff: Re: [rsheldiii/KeyV2] How can i create the 60% Layout in OpenSCAD?
  (How can i import the 60_percent_default("dcs") key(); into OpenSCAD?) (#62) 
You can call 60_percent_default from KeyV2/keys.scad
This file by default includes includes.scad which in turn includes everything you'll need from src/
I always open KeyV2/keys.scad in OpenSCAD to see what I'm doing and then just use a text editor to mess with the files in src without previewing them directly.

**Comment by rsheldiii** [comment]
sounds like this is resolved, thanks @AaronVerDow for jumping in on this
