### ISSUE TITLE
60% layout with two different Legends and Super instead of Win key?

### ISSUE THREAD

**Issue by drequivalent** [rsheldiii/KeyV2#67]
Hello. I'd like to print a 60% cherry keycap set with two requirements:
1) US-English and RU-Cyrillic layout legends
2) Instead of Win key, there should be a Super key

How do I go about doing this?

**Comment by rsheldiii** [comment]
This is actually pretty simple, I'm sorry I didn't get to you before.

here's some test code, you would replace `layouts/60_percent/default.scad` with this:

```
include <../layout.scad>

60_percent_default_layout = [
  [1,1,1,1,1,1,1,1,1,1,1,1,1,2],
  [1.5,1,1,1,1,1,1,1,1,1,1,1,1,1.5],
  [1.75,1,1,1,1,1,1,1,1,1,1,1,2.25],
  [2.25,1,1,1,1,1,1,1,1,1,1,2.75],
  [1.25,1.25,1.25,6.25,1.25,1.25,1.25,1.25]
];

60_percent_legends = [
  ["`", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", "⌫"],
  ["tab", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "[", "]", "\\"],
  ["caps", "a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "'", "enter"],
  ["shift", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/", "shift"],
  ["ctl", "super", "alt", "", "mnu", "super", "alt", "ctl"],
];

60_percent_front_legends = [
  ["Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ"],
  ["Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ"],
  ["Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ"],
  ["Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ"],
  ["Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ", "Ђ"],
];

module 60_percent_default(profile) {
  layout(60_percent_default_layout, profile, 60_percent_legends, 60_percent_front_legends) children();
}
```


and then in keys.scad you call this:


```
$font_size = 4;
60_percent_default("cherry") {
  key(); 
}
```

And it gets you this:
![image](https://user-images.githubusercontent.com/510867/154825274-cebd02f4-5935-4b85-b601-aa6fd949fdbe.png)


obviously you would have to use the actual russian legends, I'm unfamiliar with how they are laid out.



Layouts are still a beta feature and subject to change, so if you or someone else stumbles across this and wants the code to work, checkout the v2.0.2 tag.
