### ISSUE TITLE
Parallelize layout render

### ISSUE THREAD

**Issue by hacketo** [rsheldiii/KeyV2#69]
To render a blank layout of 60keys it takes ~7 min on my project.
To reduce the time to 2 min I have to render each row in a separate openscad process.
Is there any more convenient way to do it ?

**Comment by mrebersv** [comment]
This isn't a limitation of KeyV2, but rather of how OpenSCAD works.

**Comment by rsheldiii** [comment]
As @mrebersv says, parallelization is a limitation of OpenSCAD. [here's](https://github.com/openscad/openscad/issues/391) the issue tracking multi-threaded geometry rendering.

I'd love to say things have gotten better but I'm getting 9 minutes on a 60 percent layout, even after the V2 simplifications. I think this is just going to be a limitation of the library until something comes along to speed up renders.
