### ISSUE TITLE
Is there a way to define different font for legends on front and top?

### ISSUE THREAD

**Issue by nakulbende** [rsheldiii/KeyV2#71]
First of all - thanks for the wonderful repo - this is amazing! As title said, want to use front legends to depict what is going in with layers - some of these can be better represented in symbols. I am wondering if different fonts can be used. Here is the snippet I am using: 

```
include <./includes.scad>

// Basic key ID
row = 3;
column = 2;
leg = "Q";
frnt_leg = "Vol +";
//font = "Wingdings";
font = "Zilla Slab"; <--------

// Legend
leg_size = 4;
leg_top_size = 4;
leg_pos = [0,0];

// Front legend
frnt_leg_size = 3;
frnt_leg_pos = [0,-0.75];


sa_row(row) 
translate([25*column, 25*row, 0]) 
legend(leg, size=leg_size, position = leg_pos) 
front_legend(frnt_leg, size = frnt_leg_size, position = frnt_leg_pos)

        {
            // Key dimensions
            $key_length = 1;
            // Stem parameters
            $support_type = "flared";
            $stem_throw = 4;
            $stem_inset = 1;
            $stem_support_type = "disabled";
            $rounded_cherry_stem_d = 5.5;
            $cherry_bevel = true;
            // Key bump? probably only for k and d
            $key_bump = false;
            $key_bump_depth = 0.1;
            $key_bump_edge = 2;
            // Legend
            $font=font;    <-------
            $inset_legend_depth = 0.2;
            $outset_legends = false;
            // Speed it up
            $skin_extrude_shape = true;
        key();
        }
```

**Comment by osimmac** [comment]
I've been poking around this code for a week or two to generate custom keys, wandered to the issue section and saw this, figured i'd try and help, i think i've come up with the changes to get your feature working!

0.
Make a backup of your files!

1. 
in KeyV2-Master/src/settings.scad, preferably near the `$font` variable, add another called `$front_font`, you can simply copy and paste the other variable and change its name, they can have the same default value. Save changes

2.
in KeyV2-Master/src/key.scad, around line 271 there should be the `module keytext`, you can also search for it. Copy and paste it, and change the copy's name to `keytext_front` and change font variable in the line`      text(text=text, font=$font, size=font_size, halign="center", valign="center");` to be the new variable created called `$font_front`

3.
in the same file, near the bottom of the file there's a module called `legends`, the only change needed is it the lines `        for (i=[0:len($front_legends)-1]) {
          rotate([90,0,0]) keytext($front_legends[i][0], $front_legends[i][1], $front_legends[i][2], depth);`

simply change `keytext` to the new `keytext_front` module. Save changes

4.
In your key generation file, give front font unique name and assign to `$font_front`


![image](https://user-images.githubusercontent.com/33165962/98866652-83006680-242a-11eb-82b0-5b9e6a98b34e.png)


i didn't have wingdings on my system so i used other fonts, they're definitely different!

**Comment by nakulbende** [comment]
O man this is awesome, just works

Thank you so much for the help!!!

------------Sent from phone----------

Nakul Bende,

Materials Scientist, Formlabs Inc.

http://nakulbende.com

**Comment by nakulbende** [comment]
Exaclty what i wished for!
![image](https://user-images.githubusercontent.com/8712050/98876724-df747d80-244c-11eb-8c7a-774f1548307f.png)

Thanks @rsheldiii and @osimmac !
