### ISSUE TITLE
example sa_ergo produces multiple keyboards

### ISSUE THREAD

**Issue by jcress** [rsheldiii/KeyV2#74]
**What version of OpenSCAD are you on?**
2019.01

**Describe the bug**
opening sa_ergo.scad from the examples creates two keyboards

**To Reproduce**
i just opened sa_ergo.scad in openscad.

**Additional context**
![Screenshot from 2020-12-01 13-48-09](https://user-images.githubusercontent.com/6474632/100783801-3f22d080-33dc-11eb-9f0c-9debf3e9f10b.png)

**Comment by rsheldiii** [comment]
Not sure what's going on there, the code looks good. I can't repro this, it might have been fixed by something else. please reopen if you can repro
