### ISSUE TITLE
suggestion to support double extrusion printers

### ISSUE THREAD

**Issue by h3oCharles** [rsheldiii/KeyV2#79]
hey there, i was thinking of potentially printing backlit-compatible keycaps, is that possible with this library?
i know some printers allow to use two materials at once, so what if one makes a model that uses black and transparent white filaments to make a, for example, a backlit-compatible 1.75u shift?

**Comment by rsheldiii** [comment]
It's not the easiest thing to do, but there is a way to do it:

```
$inset_legend_depth = 8;
$stem_support_type = "disable";
// example key
dcs_row(5) legend("⇪", size=9) {
  key();

  difference() {
    legends($inset_legend_depth);
    inner_total_shape();
  }
}
```

This produces both the legend and the key itself, you have to comment out either the `key()` or the entire `difference()` block to get the two separate pieces. The `inner_total_shape`  difference makes sure the legend doesn't clip into the bottom of the keycap; you could also just set the support_type to "flat" and do some dead reckoning instead. It might be helpful to avoid the stem by moving the legend away from it.

I've gotten this request a few times so I think I'll try and make an example file for people to mess around with: https://github.com/rsheldiii/KeyV2/issues/138
