### ISSUE TITLE
Rotate legends on keycaps

### ISSUE THREAD

**Issue by ThajASara** [rsheldiii/KeyV2#80]
I could not find a way to rotate the direction of legends on a keycap.  For example: to model a vertical keycap for an ErgoDox style keyboard
<img width="228" alt="Screen Shot 2021-01-07 at 10 36 52 AM" src="https://user-images.githubusercontent.com/8010749/103911728-61db8f80-50d4-11eb-8f7a-5971c8b8be50.png">

Is this possible?  Did I miss something simple (highly likely)?

**Comment by AaronVerDow** [comment]
I don't know a simple solution but here is one way you could do it:
```
legend("E",[0,-1])
legend("V",[0,-1/3])
legend("A",[0,1/3])
legend("L",[0,1])
2uh()
key();
```

**Comment by mrebersv** [comment]
You can also do something like below.  Notice there can't be any indentation/spaces between the characters or the beginning/end of the line:

```
legend("E
V
A
L")
translate_u(2) 2u() sa_row(5) key();
```

**Comment by limitium** [comment]
You can modify key.scad file like that
```
module keytext(text, position, font_size, depth) {
  woffset = (top_total_key_width()/3.5) * position[0];
  hoffset = (top_total_key_height()/3.5) * -position[1];
  translate([woffset, hoffset, -depth]){
    color($tertiary_color) linear_extrude(height=$dish_depth){
      rotate([0,0,-90]) text(text=text, font=$font, size=font_size, halign="left", valign="center", direction="ttb");
    }
  }
}
```
And then you can use rotated keys with vertical label
```
translate_u(0,0) sa_row(3) {
   union(){
    2u() rotate([0,0,90]) legend("EVAL",[0,0],4) key();
  }
}
```

Result example:

![image](https://user-images.githubusercontent.com/850285/141018052-cfbbec55-befc-4d7e-870d-6dac49b13ffd.png)

**Comment by rsheldiii** [comment]
@limitium 's answer is good, though it's worth mentioning the default keystem in this library is directional; it can only fit on a keyswitch right side up or upside down, not rotated 90 or 270 degrees. if your keyswitch is rotated underneath the 2u use limitium's code, if it is the same orientation as everything else, use this code:

```
text(text=text, font=$font, size=font_size, halign="center", valign="center", direction="ttb");
```

then make a keycap like so:

```
sa_row(5) 2uh() legend("eval", size=5) key();
```

It would be good to expose the text direction in the library somehow. closing in favor of https://github.com/rsheldiii/KeyV2/issues/139
