### ISSUE TITLE
Front legends on 60% default or in customizer

### ISSUE THREAD

**Issue by toasterandpansy** [rsheldiii/KeyV2#81]
Hi, I have very little coding experience but have been picking up a little of how to utilize OpenSCAD thanks to this project :) I made an entire set of front-legend keycaps individually (not through the customizer) before I realized I could theoretically just use the premade 60% default keyboard (which would take significantly less time...) The only problem is that when I add the following to the 60% default's coding:

$front_print_legends = true;

and try to render, it comes back within seconds appearing the same. The same coding for the 60% default with top legends takes about an hour to render and the changes (such as font change) are visible. I'm not sure if I'm using the wrong code, it needs additional coding/lines to do this, or if this is just because the feature is still in beta. 

Also, as far as I can tell, the customizer has no front legend capabilities. Is there a workaround for this? 

I appreciate any advice.  I feel like I am missing something obvious. Thanks!

**Comment by AaronVerDow** [comment]
Looks like the setting in settings.scad doesn't work as advertised but I have been messing around with this and have a workaround.

Put this (or something similar) in keys.scad to draw the 60% layout:
```
60_percent_default("dcs") key();
```

Edit src/layouts/60_percent/default.scad and change:

```
    layout(60_percent_default_layout, profile, 60_percent_legends) children();
```
to: 
```
    layout(60_percent_default_layout, profile, [], 60_percent_legends) children();
```


The trick to this is here:
https://github.com/rsheldiii/KeyV2/blob/d1fec7e065f3a45ff8fd205c9d5eb51bb7566d78/src/layouts/layout.scad#L23

The layouts function accepts a layout of top legends as well as a layout for front legends.  This changes puts an empty list ([]) in place of the top legends and moves the 60_percent_legends over to the front legends position.

**Comment by rsheldiii** [comment]
@AaronVerDow has the correct answer. I want to move layouts away from giant method signatures and towards a more pure module that just sets $row and $column and renders children precisely for this reason, it will be much more extensible. Not sure when that will be happening however
