### ISSUE TITLE
What fonts/font types are supported?

### ISSUE THREAD

**Issue by ogaskell** [rsheldiii/KeyV2#94]
I'm trying to use a nerd font on my keycaps so I can include the various symbols which nerd fonts include, however when I try and use them, it just uses the default font. I've tried using the font name shown in Windows Font settings and the "Full Name", with and without `:style=Regular` however none of this seems to work.

**Comment by AaronVerDow** [comment]
I would refer to the font list from OpenSCAD Help -> Font List.  That will give an accurate representation of the exact names.  

If the names are accurate post some example code.  There are many wrong ways to set the font that's impossible to diagnose without more info.

**Comment by ogaskell** [comment]
After some googling, it seems that you have to import fonts into OpenSCAD on windows but putting them in the .fonts folder in your user's home folder. I did that with a few TTF files and it worked fine, so it's OpenSCAD being weird not KeyV2.
